### ISSUE TITLE
run npm start, get "missing script: start" when building locally

### ISSUE THREAD

**Issue by christianclover** [gakimball/supercollider#6]
Tried installing & building this documentation generator, but start script is missing. Trying to run index.js also gives errors.

**Comment by gakimball** [comment]
Sorry, the command is `npm test` to run the unit tests. I updated the readme to correct this.

**Comment by christianclover** [comment]
thanks for the quick update!

**Comment by gakimball** [comment]
@christianclover If you end up using it in an open source project, let me know, as I'm interested to see applications of this outside of just ZURB and Foundation.

**Comment by christianclover** [comment]
@gakimball still a bit unsure what to do to configure it for an open source project, but that would be ideal. If you have some pointers to get started, that would be excellent. tried running `gulp` and `supercollider -h` in the command line in supercollider main directory. Will keep experimenting.

**Comment by gakimball** [comment]
I'd look at how we have it set up in [Foundation for Sites](https://github.com/zurb/foundation-sites/tree/develop/docs/pages) for inspiration.

It's definitely not plug-and-play right now because there's no standard template. However, it was specifically designed for large projects like ours, which is why the setup is a little involved.

I'm interested in designing a standard template at some point (with Sass and JavaScript support), but I'm not sure when that will happen.
